services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coleira-tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: